<a href="https://colab.research.google.com/github/Pratibhay21/Prediction-using-Supervised-ML/blob/main/ML_NumPy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
n1=np.array([5,8,9,78])

In [3]:
n1

array([ 5,  8,  9, 78])

In [5]:
n2=np.array([[6,9,46,78],[67,56,45,34]])

In [6]:
n2

array([[ 6,  9, 46, 78],
       [67, 56, 45, 34]])

In [7]:
type(n1)

numpy.ndarray

In [9]:
n3=np.zeros((1,3))
n3
type(n3)

numpy.ndarray

In [10]:
n4=np.zeros((5,5))
n4


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
n5=np.full((2,2),10)
n5

array([[10, 10],
       [10, 10]])

In [14]:
n6=np.arange(10,20)
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
n7=np.random.randint(1,100,5)
n7

array([99,  9, 90, 95, 75])

In [22]:
n8=np.array([[4,5,6],[45,34,23]])
n8.shape
n8.shape=(3,2)
n8

array([[ 4,  5],
       [ 6, 45],
       [34, 23]])

In [27]:
n9=np.array([23,45,48])
n10=np.array([5,3,90])
n11=np.array([4,23,89])
np.vstack((n9,n10,n11))


array([[23, 45, 48],
       [ 5,  3, 90],
       [ 4, 23, 89]])

In [29]:
n9n=np.array([7,90,89,45,23])
n10n=np.array([67,78])
np.hstack((n9n,n10n))

array([ 7, 90, 89, 45, 23, 67, 78])

In [30]:
np.column_stack((n9,n10))

array([[23,  5],
       [45,  3],
       [48, 90]])

In [33]:
n12=np.array([20,80,899,90,78,40,60])
n13=np.array([90,80,60,57,30,45])
np.intersect1d(n12,n13)

array([60, 80, 90])

In [34]:
np.setdiff1d(n12,n13)

array([ 20,  40,  78, 899])

In [35]:
np.setdiff1d(n13,n12)

array([30, 45, 57])

In [40]:
n14=np.array([10,11])
n15=np.array([34,79])
np.sum([n14,n15])


134

In [43]:
np.sum([n14,n15],axis=0)


array([44, 90])

In [44]:
np.sum([n14,n15],axis=1)

array([ 21, 113])

In [45]:
n14=n14+1
n14

array([11, 12])

In [46]:
n14=n14*2
n14

array([22, 24])

In [47]:
n14=n14//8
n14

array([2, 3])

In [48]:
n14=n14-1
n14

array([1, 2])

In [49]:
n16=np.array([56,89,79,60,57])
np.mean(n16)

68.2

In [50]:
np.std(n16)

13.347658970770867

In [51]:
np.median(n16)

60.0

In [53]:
np.save('my_numpy',n16)


In [55]:
n17=np.load('my_numpy.npy')
n17

array([56, 89, 79, 60, 57])

In [60]:
import pandas as pd
s1=pd.Series([1,2,3,4,5,6])
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [58]:
type(s1)

pandas.core.series.Series

In [61]:
s1=pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f'])
s1

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [63]:
pd.Series({'a':10,'b':20,'c':30})

a    10
b    20
c    30
dtype: int64

In [64]:
pd.Series({'a':10,'b':20,'c':30},index=['b','c','d','a'])

b    20.0
c    30.0
d     NaN
a    10.0
dtype: float64

In [65]:
s1[2]

3

In [67]:
s1[-3:]

d    4
e    5
f    6
dtype: int64

In [68]:
s1[:4]

a    1
b    2
c    3
d    4
dtype: int64

In [71]:
pd.DataFrame({"name":['rani','priya','kriti'],"marks":[78,89,90]})

name  marks
0   rani     78
1  priya     89
2  kriti     90

In [101]:
iris=pd.read_csv('iris.csv')
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [102]:
iris.tail()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [103]:
iris.shape

(150, 5)

In [104]:
iris.describe()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

# New Section

In [105]:
iris.iloc[0:4,0:2]

Sepal.Length  Sepal.Width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2
3           4.6          3.1

In [109]:
iris.loc[5:10,('Sepal.Length','Species')]

Sepal.Length Species
5            5.4  setosa
6            4.6  setosa
7            5.0  setosa
8            4.4  setosa
9            4.9  setosa
10           5.4  setosa

In [114]:
iris.drop('Petal.Length',axis=1)

Sepal.Length  Sepal.Width  Petal.Width    Species
0             5.1          3.5          0.2     setosa
1             4.9          3.0          0.2     setosa
2             4.7          3.2          0.2     setosa
3             4.6          3.1          0.2     setosa
4             5.0          3.6          0.2     setosa
..            ...          ...          ...        ...
145           6.7          3.0          2.3  virginica
146           6.3          2.5          1.9  virginica
147           6.5          3.0          2.0  virginica
148           6.2          3.4          2.3  virginica
149           5.9          3.0          1.8  virginica

[150 rows x 4 columns]

In [115]:
iris.drop([1,2,3],axis=0)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[147 rows x 5 columns]

In [116]:
iris.mean()

Sepal.Length    5.843333
Sepal.Width     3.057333
Petal.Length    3.758000
Petal.Width     1.199333
dtype: float64

In [117]:
iris.median()

Sepal.Length    5.80
Sepal.Width     3.00
Petal.Length    4.35
Petal.Width     1.30
dtype: float64

In [118]:
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [119]:
def make_double(s):
  return s*2

In [120]:
iris[['Petal.Length','Sepal.Width']].apply(make_double)

Petal.Length  Sepal.Width
0             2.8          7.0
1             2.8          6.0
2             2.6          6.4
3             3.0          6.2
4             2.8          7.2
..            ...          ...
145          10.4          6.0
146          10.0          5.0
147          10.4          6.0
148          10.8          6.8
149          10.2          6.0

[150 rows x 2 columns]

In [121]:
iris['Species'].value_counts()

setosa        50
versicolor    50
virginica     50
Name: Species, dtype: int64

In [127]:
iris.sort_values(by='Sepal.Length')

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
13            4.3          3.0           1.1          0.1     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
41            4.5          2.3           1.3          0.3     setosa
..            ...          ...           ...          ...        ...
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica
131           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]